# Generated by Django 5.0.6 on 2025-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_event", models.DateField()),
                ("maximum_event", models.DateField()),
                ("end_event", models.DateField(null=True)),
                ("min_freq", models.FloatField()),
                ("max_freq", models.FloatField()),
                (
                    "tag",
                    models.IntegerField(
                        choices=[(0, "flare"), (1, "background"), (2, "artifact")],
                        default=0,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlareList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("num_flare", models.PositiveIntegerField(null=True)),
                ("diagram", models.ImageField(null=True, upload_to="img/")),
                ("csv_file", models.FileField(null=True, upload_to="csv/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.DeleteModel(
            name="Catalouge",
        ),
    ]
