# Generated by Django 5.0.6 on 2024-06-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalouge',
            new_name='Catalogue',
        ),
    ]
