# Generated by Django 5.0.6 on 2024-06-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_rename_catalouge_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='image',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
    ]
