# Generated by Django 5.0.6 on 2025-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_flare_flarelist_delete_catalouge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flare",
            name="end_event",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="flare",
            name="maximum_event",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="flare",
            name="start_event",
            field=models.DateTimeField(),
        ),
    ]
