# Generated by Django 5.0.6 on 2025-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_flare_end_event_alter_flare_maximum_event_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FlareList",
        ),
        migrations.AlterField(
            model_name="flare",
            name="tag",
            field=models.IntegerField(
                choices=[(0, "flare"), (1, "background"), (2, "artifact")], default=2
            ),
        ),
    ]
