# Generated by Django 5.0.6 on 2024-10-25 03:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_catalogue_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("summary", models.TextField()),
                ("diagram", models.FileField(blank=True, upload_to="img/")),
            ],
        ),
        migrations.CreateModel(
            name="YearMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2023)]
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Catalogue",
        ),
        migrations.AddField(
            model_name="summaryday",
            name="year_month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.yearmonth"
            ),
        ),
    ]
