# Generated by Django 5.0.6 on 2024-10-25 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_summaryday_yearmonth_delete_catalogue_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summaryday",
            name="title",
        ),
        migrations.AddField(
            model_name="summaryday",
            name="day",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="yearmonth",
            name="year_month_title",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="summaryday",
            name="summary",
            field=models.CharField(max_length=25),
        ),
    ]
