# Generated by Django 5.0.6 on 2024-10-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_remove_summaryday_title_summaryday_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yearmonth",
            name="year_month_title",
        ),
    ]
