# Generated by Django 5.0.6 on 2024-10-25 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_remove_yearmonth_year_month_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summaryday",
            name="summary",
        ),
        migrations.AddField(
            model_name="summaryday",
            name="flare_num",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="summaryday",
            name="day",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ]
            ),
        ),
    ]
