# Generated by Django 5.0.6 on 2024-11-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_remove_summaryday_summary_summaryday_flare_num_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SummaryDay",
            new_name="DayFlareList",
        ),
    ]
