# Generated by Django 5.0.6 on 2024-11-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_rename_summaryday_dayflarelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlareList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("num_flare", models.PositiveIntegerField(null=True)),
                ("diagram", models.FileField(null=True, upload_to="img/")),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="catalogue_f_date_e5d404_idx")
                ],
            },
        ),
    ]
