# Generated by Django 5.0.6 on 2024-11-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_flarelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="flarelist",
            name="csv_file",
            field=models.FileField(null=True, upload_to="csv/"),
        ),
    ]
