# Generated by Django 5.0.6 on 2024-11-28 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_flarelist_csv_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_event", models.TimeField()),
                ("maximum_event", models.TimeField()),
                ("finish_event", models.TimeField()),
                ("min_freq", models.FloatField()),
                ("max_freq", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="dayflarelist",
            name="year_month",
        ),
        migrations.AlterModelOptions(
            name="flarelist",
            options={"ordering": ["date"]},
        ),
        migrations.RemoveIndex(
            model_name="flarelist",
            name="catalogue_f_date_e5d404_idx",
        ),
        migrations.AlterField(
            model_name="flarelist",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="flare",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.flarelist"
            ),
        ),
        migrations.DeleteModel(
            name="DayFlareList",
        ),
        migrations.DeleteModel(
            name="YearMonth",
        ),
    ]
