# Generated by Django 5.0.6 on 2024-11-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0012_flarelist_date_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestFlare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_event", models.TimeField()),
                ("maximum_event", models.TimeField()),
                ("finish_event", models.TimeField()),
                ("min_freq", models.FloatField()),
                ("max_freq", models.FloatField()),
            ],
        ),
    ]
