# Generated by Django 5.0.6 on 2024-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_testflare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testflare",
            name="finish_event",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="maximum_event",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="start_event",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
