# Generated by Django 5.0.6 on 2024-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0014_alter_testflare_finish_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testflare",
            name="max_freq",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="min_freq",
            field=models.FloatField(null=True),
        ),
    ]
