# Generated by Django 5.0.6 on 2024-11-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0015_alter_testflare_max_freq_alter_testflare_min_freq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testflare",
            name="finish_event",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="max_freq",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="maximum_event",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="min_freq",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="start_event",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
