# Generated by Django 5.0.6 on 2024-11-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0016_alter_testflare_finish_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testflare",
            name="finish_event",
            field=models.CharField(
                max_length=10, null=True, verbose_name="finish event"
            ),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="max_freq",
            field=models.CharField(
                max_length=10, null=True, verbose_name="max freq GHz"
            ),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="maximum_event",
            field=models.CharField(
                max_length=10, null=True, verbose_name="maximum event"
            ),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="min_freq",
            field=models.CharField(
                max_length=10, null=True, verbose_name="min freq GHz"
            ),
        ),
        migrations.AlterField(
            model_name="testflare",
            name="start_event",
            field=models.CharField(
                max_length=10, null=True, verbose_name="start event"
            ),
        ),
    ]
