# Generated by Django 5.0.6 on 2024-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0017_alter_testflare_finish_event_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestFlare",
        ),
        migrations.AlterField(
            model_name="flarelist",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="flarelist",
            name="diagram",
            field=models.ImageField(null=True, upload_to="img/"),
        ),
    ]
