# Generated by Django 5.0.6 on 2024-12-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0018_delete_testflare_alter_flarelist_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flarelist",
            name="date",
            field=models.DateField(),
        ),
    ]
