# Generated by Django 5.0.6 on 2025-03-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0021_alter_flarelist_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="flare",
            name="tag",
            field=models.IntegerField(
                choices=[(0, "flare"), (1, "background"), (2, "artifact")], default=0
            ),
        ),
    ]
