# Generated by Django 5.0.6 on 2025-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_flare_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="flare",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
