# Generated by Django 5.0.6 on 2024-06-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_publications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
