# Generated by Django 5.0.6 on 2024-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_publications_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_conf', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('place', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('first_author', models.CharField(max_length=30)),
                ('authors', models.TextField()),
            ],
        ),
    ]
