# Generated by Django 5.0.6 on 2024-06-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_conference_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='id_conf',
            field=models.IntegerField(null=True),
        ),
    ]
