# Generated by Django 5.0.6 on 2024-06-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_presentation_id_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
