# Generated by Django 5.0.6 on 2024-06-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_conference_id_alter_presentation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='id_conf',
        ),
        migrations.AddField(
            model_name='presentation',
            name='conf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.conference'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
