# Generated by Django 5.0.6 on 2024-07-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_presentation_options_conference_url_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='page',
            field=models.IntegerField(null=True),
        ),
    ]
