# Generated by Django 5.0.6 on 2024-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_conference_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='page',
        ),
        migrations.AddField(
            model_name='presentation',
            name='page',
            field=models.IntegerField(null=True),
        ),
    ]
