# Generated by Django 5.0.6 on 2024-10-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_conference_page_presentation_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="email",
            new_name="part",
        ),
    ]
