# Generated by Django 5.0.6 on 2024-10-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_rename_email_team_part"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="presentation",
            options={"ordering": ["-type", "first_author"]},
        ),
    ]
