# Generated by Django 5.0.6 on 2024-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_presentation_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proceedings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authors", models.TextField()),
                ("title", models.TextField()),
                ("journal", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("parameters", models.CharField(blank=True, max_length=20, null=True)),
                ("doi", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="conference",
            name="url_abstract",
            field=models.URLField(blank=True, null=True),
        ),
    ]
