# Generated by Django 5.0.6 on 2024-10-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_proceedings_alter_conference_url_abstract"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proceedings",
            options={
                "verbose_name": "Proceeding",
                "verbose_name_plural": "Proceedings",
            },
        ),
        migrations.AlterField(
            model_name="proceedings",
            name="journal",
            field=models.TextField(),
        ),
    ]
