# Generated by Django 5.0.6 on 2024-11-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_proceedings_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceedings",
            name="doi",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
