# Generated by Django 5.0.6 on 2024-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_proceedings_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="date",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="type",
            field=models.CharField(
                choices=[("talk", "Устный доклад"), ("poster", "Постер")], max_length=6
            ),
        ),
    ]
