# Generated by Django 5.0.6 on 2025-01-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_conference_date_alter_presentation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="pdf",
            field=models.BinaryField(null=True),
        ),
    ]
