# Generated by Django 5.0.6 on 2025-03-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_presentation_pdf"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PDF",
        ),
    ]
